# =============================================
# Configuración de Base de Datos MySQL
# =============================================
db.host=localhost
db.port=3306
db.name=crud_usuarios
db.username=root
db.password=1043657193Mmm

# =============================================
# Configuración SMTP (JavaMail)
# =============================================
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=mortegas4@unicartagena.edu.co
smtp.password=ikoe bfce trkp kvpu
smtp.from.address=mortegas4@unicartagena.edu.co
smtp.from.name=Gestión de Usuarios

